/**
 * Solver adapter pattern (spec: "Solver adapter selected at runtime").
 * - builtin: in-process 3D finite-volume solver (always available).
 * - icepak / flotherm / starccm / fluent / custom: generate a solver input deck and,
 *   when the executable or API endpoint is reachable, launch it in batch mode.
 *   External solvers are expected to write `results.json` (ThermalResults subset) next to the deck.
 */
import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { SOLVER_LABELS, type ProjectDoc, type Solver, type ThermalResults } from '@ats/shared';
import { runSimulation, type RunHooks } from '../engine/run';
import { buildModel } from '../engine/geometry';
import { JOB_DIR } from '../db';

export interface SolverStatus {
  type: Solver['type'];
  label: string;
  connected: boolean;
  licenseStatus: 'Available' | 'Busy' | 'Missing';
  version: string;
  message: string;
  checks: { label: string; ok: boolean }[];
}

export interface SolverAdapter {
  type: Solver['type'];
  label: string;
  status(cfg: Solver, busy: boolean): Promise<SolverStatus>;
  exportDeck(doc: ProjectDoc): { filename: string; content: string };
  run(doc: ProjectDoc, jobId: string, hooks: RunHooks): Promise<ThermalResults>;
}

// ------------------------------------------------------------------ builtin
const builtin: SolverAdapter = {
  type: 'builtin',
  label: SOLVER_LABELS.builtin,
  async status(_cfg, busy) {
    return {
      type: 'builtin', label: SOLVER_LABELS.builtin, connected: true, licenseStatus: busy ? 'Busy' : 'Available', version: '1.0',
      message: busy ? 'Solver busy with another job' : 'Connected',
      checks: [
        { label: 'License OK', ok: true },
        { label: 'Solver Ready', ok: !busy },
        { label: 'Model Import/Export', ok: true },
        { label: 'AI Optimization Enabled', ok: true },
      ],
    };
  },
  exportDeck(doc) { return { filename: `${doc.project.id}_model.json`, content: JSON.stringify(buildModel(doc), null, 2) }; },
  run: (doc, jobId, hooks) => runSimulation(doc, jobId, hooks),
};

// ------------------------------------------------------------------ external
function icepakScript(doc: ProjectDoc): string {
  const m = buildModel(doc);
  const lines = [
    '# Auto-generated by AI Thermal Simulator — PyAEDT (Ansys Icepak) batch script',
    '# Usage: ansysedt -ng -RunScriptAndExit icepak_model.py   (or: python icepak_model.py with pyaedt installed)',
    'import json, os',
    'from ansys.aedt.core import Icepak',
    `ipk = Icepak(project="${doc.project.id}", design="${doc.jedec.standard.replace(/[^A-Za-z0-9]/g, '_')}", non_graphical=True, new_desktop=True)`,
    'ipk.modeler.model_units = "mm"',
    `ipk.globalMeshSettings(meshtype=${doc.simulation.mesh.density === 'fine' ? 3 : doc.simulation.mesh.density === 'coarse' ? 1 : 2})`,
    '',
  ];
  const mats = new Map<string, string>();
  m.blocks.forEach((b, i) => {
    const key = `${b.kx}_${b.ky}_${b.kz}_${b.rho}_${b.cp}`;
    if (!mats.has(key)) {
      const name = `ats_mat_${mats.size + 1}`;
      mats.set(key, name);
      lines.push(`mat = ipk.materials.add_material("${name}")`, `mat.thermal_conductivity = [${b.kx}, ${b.ky}, ${b.kz}]`, `mat.mass_density = ${b.rho}`, `mat.specific_heat = ${b.cp}`);
    }
    lines.push(`b${i} = ipk.modeler.create_box([${b.x0}, ${b.y0}, ${b.z0}], [${+(b.x1 - b.x0).toFixed(5)}, ${+(b.y1 - b.y0).toFixed(5)}, ${+(b.z1 - b.z0).toFixed(5)}], name="${b.name.replace(/[^A-Za-z0-9]/g, '_')}_${i}", material="${mats.get(key)}")`);
  });
  m.dies.forEach((d, i) => lines.push(`ipk.assign_source("${doc.package.dies[i].name.replace(/[^A-Za-z0-9]/g, '_')}_${m.blocks.findIndex((b) => b.role === 'die' && b.dieIndex === i)}", "Total Power", "${d.power}W")`));
  lines.push(
    '',
    `ipk.modeler.create_air_region(x_pos=50, y_pos=50, z_pos=100, x_neg=50, y_neg=50, z_neg=50, is_percentage=True)`,
    `ipk.assign_openings(ipk.modeler.get_object_faces("Region"))`,
    `setup = ipk.create_setup("JEDEC")`,
    `setup.props["Convergence Criteria - Energy"] = ${doc.simulation.convergence.energy}`,
    `setup.props["Convergence Criteria - Max Iterations"] = ${doc.simulation.convergence.maxIter}`,
    `setup.props["Include Gravity"] = True`,
    `setup.props["Ambient Temperature"] = "${doc.simulation.ambientTemp}cel"`,
    'ipk.analyze()',
    '# Export summary for AI Thermal Simulator',
    'tmax = ipk.post.get_scalar_field_value("Temperature", "Maximum", object_name="' + doc.package.dies[0].name.replace(/[^A-Za-z0-9]/g, '_') + '_' + m.blocks.findIndex((b) => b.role === 'die') + '")',
    `json.dump({"tjMax": tmax, "power": ${m.totalPower}, "ambientTemp": ${doc.simulation.ambientTemp}}, open(os.path.join(os.path.dirname(__file__), "results.json"), "w"))`,
    'ipk.release_desktop()',
  );
  return lines.join('\n');
}

function floxml(doc: ProjectDoc): string {
  const m = buildModel(doc);
  const esc = (s: string) => s.replace(/[<>&"]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;' })[c]!);
  const cuboids = m.blocks.map((b, i) => `      <cuboid>
        <name>${esc(b.name)}_${i}</name>
        <position><x>${b.x0 / 1000}</x><y>${b.y0 / 1000}</y><z>${b.z0 / 1000}</z></position>
        <size><x>${(b.x1 - b.x0) / 1000}</x><y>${(b.y1 - b.y0) / 1000}</y><z>${(b.z1 - b.z0) / 1000}</z></size>
        <material>ats_${i}</material>${b.role === 'die' ? `\n        <thermal>die_power_${b.dieIndex}</thermal>` : ''}
      </cuboid>`).join('\n');
  const materials = m.blocks.map((b, i) => `    <orthotropic_material><name>ats_${i}</name><x_conductivity>${b.kx}</x_conductivity><y_conductivity>${b.ky}</y_conductivity><z_conductivity>${b.kz}</z_conductivity><density>${b.rho}</density><specific_heat>${b.cp}</specific_heat></orthotropic_material>`).join('\n');
  const thermals = m.dies.map((d) => `    <thermal_att><name>die_power_${d.index}</name><thermal_model>conduction</thermal_model><power>${d.power}</power></thermal_att>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by AI Thermal Simulator — Simcenter FloTHERM FloXML (SI units) -->
<xml_case>
  <name>${esc(doc.project.name)}</name>
  <model>
    <modeling><solution>flow_heat</solution><radiation>${doc.simulation.includeRadiation ? 'on' : 'off'}</radiation><dimensionality>3d</dimensionality><transient>${doc.simulation.type === 'transient' ? 'true' : 'false'}</transient></modeling>
    <turbulence><type>${doc.simulation.airVelocity > 0 ? 'turbulent' : 'laminar'}</type></turbulence>
    <gravity><type>normal</type><normal_direction>${doc.package.orientation === 'Vertical' ? 'neg_y' : 'neg_z'}</normal_direction></gravity>
    <global><ambient_temperature>${doc.simulation.ambientTemp}</ambient_temperature></global>
  </model>
  <solve><overall_control><outer_iterations>${doc.simulation.convergence.maxIter}</outer_iterations></overall_control></solve>
  <attributes>
    <materials>
${materials}
    </materials>
    <thermals>
${thermals}
    </thermals>
  </attributes>
  <geometry>
    <assembly><name>${esc(doc.package.type)}_on_${doc.jedec.boardType}</name><geometry>
${cuboids}
    </geometry></assembly>
  </geometry>
</xml_case>
`;
}

const BATCH: Record<string, { deck: (d: ProjectDoc) => { filename: string; content: string }; args: (deck: string) => string[] }> = {
  icepak: { deck: (d) => ({ filename: 'icepak_model.py', content: icepakScript(d) }), args: (f) => ['-ng', '-RunScriptAndExit', f] },
  flotherm: { deck: (d) => ({ filename: 'flotherm_model.xml', content: floxml(d) }), args: (f) => ['-b', f] },
  starccm: { deck: (d) => ({ filename: 'starccm_model.json', content: JSON.stringify(buildModel(d), null, 2) }), args: (f) => ['-batch', f] },
  fluent: { deck: (d) => ({ filename: 'fluent_model.json', content: JSON.stringify(buildModel(d), null, 2) }), args: (f) => ['3ddp', '-g', '-i', f] },
  custom: { deck: (d) => ({ filename: 'model.json', content: JSON.stringify({ project: d, model: buildModel(d) }, null, 2) }), args: (f) => [f] },
};

async function endpointReachable(endpoint: string): Promise<{ ok: boolean; kind: 'url' | 'path' | 'none' }> {
  if (!endpoint) return { ok: false, kind: 'none' };
  if (/^https?:\/\//i.test(endpoint)) {
    try {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 2500);
      const r = await fetch(endpoint, { signal: ctrl.signal });
      clearTimeout(t);
      return { ok: r.status < 500, kind: 'url' };
    } catch { return { ok: false, kind: 'url' }; }
  }
  return { ok: fs.existsSync(endpoint), kind: 'path' };
}

function external(type: Exclude<Solver['type'], 'builtin'>): SolverAdapter {
  const label = SOLVER_LABELS[type];
  const b = BATCH[type];
  return {
    type, label,
    async status(cfg, busy) {
      const r = await endpointReachable(cfg.endpoint);
      const lic = r.ok ? (busy ? 'Busy' : 'Available') : 'Missing';
      return {
        type, label, connected: r.ok, licenseStatus: lic, version: cfg.version || 'unknown',
        message: r.ok ? 'Connected' : r.kind === 'none' ? 'No executable / endpoint configured' : `Not reachable: ${cfg.endpoint}`,
        checks: [
          { label: 'License OK', ok: r.ok },
          { label: 'Solver Ready', ok: r.ok && !busy },
          { label: 'Model Import/Export', ok: true },
          { label: 'AI Optimization Enabled', ok: true },
        ],
      };
    },
    exportDeck: b.deck,
    async run(doc, jobId, hooks) {
      const dir = path.join(JOB_DIR, jobId);
      fs.mkdirSync(dir, { recursive: true });
      const deck = b.deck(doc);
      const deckPath = path.join(dir, deck.filename);
      fs.writeFileSync(deckPath, deck.content);
      hooks.log(`${label}: input deck written to ${deckPath}`);
      const reach = await endpointReachable(doc.solver.endpoint);
      if (!reach.ok || reach.kind !== 'path') {
        throw new Error(`${label} executable not available (${doc.solver.endpoint || 'no endpoint'}). Deck exported; enable "fallback to built-in solver" or install/configure the solver.`);
      }
      hooks.progress(10, `Running ${label}`);
      await new Promise<void>((resolve, reject) => {
        const p = spawn(doc.solver.endpoint, b.args(deckPath), { cwd: dir });
        p.stdout.on('data', (d) => String(d).split(/\r?\n/).filter(Boolean).forEach((l) => hooks.log(l)));
        p.stderr.on('data', (d) => String(d).split(/\r?\n/).filter(Boolean).forEach((l) => hooks.log('ERR ' + l)));
        const iv = setInterval(() => { if (hooks.isCancelled()) { p.kill(); clearInterval(iv); reject(new Error('Job cancelled')); } }, 500);
        p.on('error', (e) => { clearInterval(iv); reject(e); });
        p.on('close', (code) => { clearInterval(iv); code === 0 ? resolve() : reject(new Error(`${label} exited with code ${code}`)); });
      });
      const resPath = path.join(dir, 'results.json');
      if (!fs.existsSync(resPath)) throw new Error(`${label} finished but results.json was not produced.`);
      const ext = JSON.parse(fs.readFileSync(resPath, 'utf8')) as Partial<ThermalResults>;
      // complete missing post-processing with the built-in engine, then overlay solver values
      hooks.log('Post-processing with built-in engine for maps and JEDEC metrics; overlaying external solver values.');
      const base = await runSimulation(doc, jobId, { ...hooks, progress: (p, s) => hooks.progress(60 + p * 0.4, s) });
      return { ...base, ...ext, solver: label, thetaJA: ext.tjMax != null ? +((ext.tjMax - base.ambientTemp) / base.power).toFixed(3) : base.thetaJA };
    },
  };
}

export const adapters: Record<Solver['type'], SolverAdapter> = {
  builtin,
  icepak: external('icepak'),
  flotherm: external('flotherm'),
  starccm: external('starccm'),
  fluent: external('fluent'),
  custom: external('custom'),
};
